[package]
name = "aoc"
version = "0.1.0"
edition = "2021"

[dependencies]
rust-crypto = "0.2.36"
itertools = "0.14.0"
num = "0.4.1"
rayon = "1.8.0"
nom = "7.1.3"
cargo-aoc = "0.3.8"
clap = "4.5.26"
serde = "1.0.193"
serde_derive = "1.0.193"
serde_json = "1.0.108"
